### ISSUE TITLE
search.php not compatible with multiple Store Views

### ISSUE THREAD

**Issue by paugnu** [Web200/magento-elasticsuite-autocomplete#2]
Hi,

First of all, I would like to thank you for making this module public, c'est vraiment cool :)

I've seen that you make some changes here: https://github.com/Web200/magento-elasticsuite-autocomplete/commit/562aaca5d2e5d44f6e197c96bcb21aa16e9d4ee3

But in our tests, results are still not correct when using search.php in multiple stores.

We have:
* Magento 2.4.2-p1
* 3 store views (EN, FR, ES)

When we enable the search.php in the form.mini.phtml file:
* We get wrong results which include products from other store views (and missing products from current store).

If we use the controller, it works fine.

**Comment by kpitn** [comment]
Hi @paugnu ,

Thanks your kind words.

I discover this bug, but it's already fix in last release.

https://github.com/Web200/magento-elasticsuite-autocomplete/commit/562aaca5d2e5d44f6e197c96bcb21aa16e9d4ee3

Perhaps the file search.php is not overwrite on module update ?

Did you use composer install when you deploy your magento ?

**Comment by paugnu** [comment]
Hi Pierre,

I've tested it again and it's fixed. I'm not sure why it didn't work the first time.

Thanks a lot!

**Comment by paugnu** [comment]
Hi Pierre,

I talked too fast. Actually, the search by store didn't work. 

There are many reasons:
* The url created by $block->getUrl('', ['_direct' => 'search.php']) contains the store_code. I get a 404 result when the search.php is called
* I've used used a $baseUrl param (without the store code) to call search.php. The problem is that the param $_SERVER[StoreManager::PARAM_RUN_CODE] is empty. As a result, we were receiving results from all the stores

To solve this last point, I've added a store_code param to the search.php call, with the store code and updated the search.php to use that param. I guess the solution to the very first point might be using a different nginx configuration?

**Comment by kpitn** [comment]
I understand, I just publish a new version : https://github.com/Web200/magento-elasticsuite-autocomplete/commit/56a83bca21e06ee613b4ee370ab65d8777b512f4

Tell me if your problem is solve.

Now you need to use this syntax if you dont want to use magento rooting : 
```
"url":"<?= $block->getFormViewModel()->getSearchUrl() ?>",
````

**Comment by paugnu** [comment]
Hi Pierre,

Tested, it works fine now. Parfait!
