### ISSUE TITLE
Autocomplete results don't include store code in product URL

### ISSUE THREAD

**Issue by paugnu** [Web200/magento-elasticsuite-autocomplete#3]
Hi,

I've found a weird issue. We have 3 store views set up as subfolers (/es, /en, /fr).

When using the default search by Smile, the autocomplete results include the store code in their url. But when using either:
`"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('autocomplete'); ?>",`

Or the search.php, I get results without the store code in their url. That results in a 404 page.

**Comment by kpitn** [comment]
It's fix in last version, thank for your contribution
